US_AMERICA:
  - "United States"

AMERICA:
  - "Canada"
  - "Mexico"
  - "Brazil"
  - "Chile"
  - "Argentina"

EU:
  - "Germany"
  - "United Kingdom"
  - "France"
  - "Spain"
  - "Netherlands"
  - "Sweden"
  - "Italy"
  - "Switzerland"
  - "Poland"
  - "Finland"
  - "Denmark"
  - "Ireland"
  - "Belgium"
  - "Austria"
  - "Portugal"
  - "Greece"
  - "Luxembourg"
  - "Czech Republic"
  - "Iceland"
  - "EU"
  - "European Union"
  - "Europe"

ASIA:
  - "China"
  - "Japan"
  - "South Korea"
  - "Hong Kong"
  - "Singapore"
  - "Taiwan"
  - "Thailand"
  - "India"
  - "Indonesia"
  - "Philippines"
  - "Vietnam"
  - "Malaysia"
  - "Pakistan"
  - "Cambodia"
  - "Asia"

MIDDLE EAST:
  - "Saudi Arabia"
  - "United Arab Emirates"
  - "Israel"
  - "Qatar"
  - "Bahrain"
  - "Oman"
  - "Kuwait"
  - "Turkey"

OTHERS:
  - "Australia"
  - "New Zealand"
  - "South Africa"
  - "Norway"
  - "Russia"

GLOBAL:
  - "Global"