STOCKS:
    - "MSFT"
    - "AAPL"
    - "GOOG"
    - "NVDA"
    - "AMZN"
    - "META"
    - "BRK-B"
    - "LLY"
    - "AVGO"
    - "V"
    - "JPM"
    - "NVO"
    - "MC.PA"
    - "ASML"
    - "RMS.PA"
    - "OR.PA"
    - "SAP"
    - "ACN"
    - "TTE"
    - "SIE.DE"
    - "IDEXY"
    - "CDI.PA"
    - "RELIANCE.NS"
    - "TCS.NS"
    - "HDB"
    - "BHARTIARTL.NS"
    - "IBN"
    - "SBIN.NS"
    - "LICI.NS"
    - "INFY"
    - "ITC.NS"
    - "HINDUNILVR.NS"
    - "LT.NS"

MACRO:
- "^GDAXI"
- "^GSPC"
- "^DJI"
- "EPI" 
- ^VIX
- GC=F
- CL=F
- BZ=F
- BTC-USD

MACRO_PDR:
  DGS1: null
  DGS5: null
  DGS10: null
  CPILFESL: 1 # 1 month lag
  FEDFUNDS: 1 # 1 month lag
  GDPPOT: null