# Extensive ETF and Index Symbols to Country/Region Mapping

# US_AMERICA
United States:
  - "SPY"  # SPDR S&P 500 ETF
  - "QQQ"  # Invesco QQQ Trust (NASDAQ-100)
  - "VOO"  # Vanguard S&P 500 ETF
  - "IVV"  # iShares Core S&P 500 ETF
  - "DIA"  # SPDR Dow Jones Industrial Average ETF
  - "^GSPC"  # S&P 500 Index
  - "^DJI"  # Dow Jones Industrial Average
  - "^IXIC"  # NASDAQ Composite
  - "^RUT"  # Russell 2000 Index
  - "IWM"  # iShares Russell 2000 ETF
  - "VTI"  # Vanguard Total Stock Market ETF
  - "SCHD"  # Schwab US Dividend Equity ETF
  - "XLK"  # Technology Select Sector SPDR Fund
  - "XLF"  # Financial Select Sector SPDR Fund
  - "XLE"  # Energy Select Sector SPDR Fund
  - "XLV"  # Health Care Select Sector SPDR Fund
  - "XLY"  # Consumer Discretionary Select Sector SPDR Fund
  - "XLP"  # Consumer Staples Select Sector SPDR Fund
  - "XLI"  # Industrial Select Sector SPDR Fund
  - "XLU"  # Utilities Select Sector SPDR Fund
  - "XLB"  # Materials Select Sector SPDR Fund
  - "^VIX"  # CBOE Volatility Index

  # BONDS
  - "TLT"  # iShares 20+ Year Treasury Bond ETF
  - "IEF"  # iShares 7-10 Year Treasury Bond ETF
  - "HYG"  # iShares iBoxx $ High Yield Corporate Bond ETF
  - "LQD"  # iShares iBoxx $ Investment Grade Corporate Bond ETF
  - "BND"  # Vanguard Total Bond Market ETF
  - "AGG"  # iShares Core U.S. Aggregate Bond ETF

  # COMMODITIES
  - "CL=F" # WTI Crude Oil Futures


# CANADA
Canada:
  - "EWC"  # iShares MSCI Canada ETF
  - "^GSPTSE"  # S&P/TSX Composite Index
  - "XIU"  # iShares S&P/TSX 60 Index ETF
  - "ZCN"  # BMO S&P/TSX Capped Composite Index ETF

# LATIN AMERICA
Brazil:
  - "EWZ"  # iShares MSCI Brazil ETF
  - "^BVSP"  # Bovespa Index

Mexico:
  - "EWW"  # iShares MSCI Mexico ETF
  - "^MXX"  # IPC Index

Latin America:
  - "ILF"  # iShares Latin America 40 ETF
  - "GML"  # SPDR S&P Emerging Latin America ETF

# EUROPE
European Union:
  - "EZU"  # iShares MSCI Eurozone ETF
  - "FEZ"  # SPDR Euro Stoxx 50 ETF
  - "^STOXX50E"  # Euro Stoxx 50 Index
  - "HEDJ"  # WisdomTree Europe Hedged Equity ETF

Europe:
  - "VGK"  # Vanguard FTSE Europe ETF
  - "IEV"  # iShares Europe ETF
  - "BZ=F" # Brent Crude Oil Futures

Germany:
  - "EWG"  # iShares MSCI Germany ETF
  - "^GDAXI"  # DAX Index

France:
  - "EWQ"  # iShares MSCI France ETF
  - "^FCHI"  # CAC 40 Index

United Kingdom:
  - "EWU"  # iShares MSCI United Kingdom ETF
  - "^FTSE"  # FTSE 100 Index

Italy:
  - "EWI"  # iShares MSCI Italy ETF
  - "^FTMIB"  # FTSE MIB Index

Spain:
  - "EWP"  # iShares MSCI Spain ETF
  - "^IBEX"  # IBEX 35 Index

Sweden:
  - "EWD"  # iShares MSCI Sweden ETF
  - "^OMX"  # OMX Stockholm 30 Index

Netherlands:
  - "EWN"  # iShares MSCI Netherlands ETF
  - "^AEX"  # AEX Index

Belgium:
  - "EWK"  # iShares MSCI Belgium ETF
  - "^BEL20"  # BEL 20 Index

# ASIA
Hong Kong:
  - "EWH"  # iShares MSCI Hong Kong ETF
  - "^HSI"  # Hang Seng Index
  - "2800"  # Tracker Fund of Hong Kong

Japan:
  - "EWJ"  # iShares MSCI Japan ETF
  - "^N225"  # Nikkei 225 Index
  - "DXJ"  # WisdomTree Japan Hedged Equity ETF

Taiwan:
  - "EWT"  # iShares MSCI Taiwan ETF
  - "^TWII"  # Taiwan Weighted Index

Singapore:
  - "EWS"  # iShares MSCI Singapore ETF
  - "^STI"  # Straits Times Index

South Korea:
  - "EWY"  # iShares MSCI South Korea ETF
  - "^KS11"  # KOSPI Index

Indonesia:
  - "EIDO"  # iShares MSCI Indonesia ETF
  - "^JKSE"  # Jakarta Composite Index

Philippines:
  - "EPHE"  # iShares MSCI Philippines ETF
  - "^PSEI"  # PSE Composite Index

Malaysia:
  - "EWM"  # iShares MSCI Malaysia ETF
  - "^KLSE"  # FTSE Bursa Malaysia KLCI Index

Asia-Pacific:
  - "EPP"  # iShares MSCI Pacific ex-Japan ETF
  - "AAXJ"  # iShares MSCI All Country Asia ex-Japan ETF

# CHINA
China:
  - "MCHI"  # iShares MSCI China ETF
  - "FXI"  # iShares China Large-Cap ETF
  - "^SSEC"  # Shanghai Composite Index
  - "KWEB"  # KraneShares CSI China Internet ETF
  - "ASHR"  # Xtrackers Harvest CSI 300 China A-Shares ETF

# INDIA
India:
  - "INDA"  # iShares MSCI India ETF
  - "EPI"  # WisdomTree India Earnings Fund
  - "^NSEI"  # Nifty 50 Index
  - "^BSESN"  # BSE SENSEX Index

# MIDDLE EAST
Israel:
  - "EIS"  # iShares MSCI Israel ETF
  - "^TA125"  # TA-125 Index

Saudi Arabia:
  - "KSA"  # iShares MSCI Saudi Arabia ETF
  - "^TASI"  # Tadawul All Share Index

United Arab Emirates:
  - "UAE"  # iShares MSCI UAE ETF
  - "^DFMGI"  # Dubai Financial Market General Index

# AFRICA
South Africa:
  - "EZA"  # iShares MSCI South Africa ETF
  - "^JALSH"  # FTSE/JSE All Share Index

# GLOBAL/REGIONAL
Global:
  - "VT"  # Vanguard Total World Stock ETF
  - "ACWI"  # iShares MSCI ACWI ETF
  - "VEU"  # Vanguard FTSE All-World ex-US ETF
  - "VXUS"  # Vanguard Total International Stock ETF
  - "BTC-USD" # Bitcoin

# COMMODITIES
  - "GLD"  # SPDR Gold Shares
  - "GC=F" # Gold futures
  - "SLV"  # iShares Silver Trust
  - "USO"  # United States Oil Fund
  - "UNG"  # United States Natural Gas Fund
  - "DBA"  # Invesco DB Agriculture Fund

Developed Markets:
  - "EFA"  # iShares MSCI EAFE ETF

Emerging Markets:
  - "EEM"  # iShares MSCI Emerging Markets ETF
  - "SCHE"  # Schwab Emerging Markets Equity ETF
  - "VWO"  # Vanguard FTSE Emerging Markets ETF
  - "IEMG"  # iShares Core MSCI Emerging Markets ETF



